import { ScaleBluetoothIds } from '@enums/ScaleBluetoothIds'
import Connect from '@modules/connect/Connect'
import Graph from '@modules/graph/Graph'
import Scale from '@modules/scale/Scale'
import { Box, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'


const scaleDeviceRequestOptions: RequestDeviceOptions = {
  optionalServices: [ScaleBluetoothIds.PRIMARY_SERVICE_ID],
  acceptAllDevices: true
}

const Home: NextPage = () => {
  const [alignment, setAlignment] = useState('scale');

  const handleChange = (event: any, newAlignment: any) => {
    setAlignment(newAlignment);
  };
  const [bluetoothDevice, setBluetoothDevice] = useState<BluetoothDevice | null>(null)
  const findDevice = async () => {
    const foundBluetoothDevice = await navigator.bluetooth.requestDevice(scaleDeviceRequestOptions)
      .catch((error: any) => { console.log(error.message) })

    if (foundBluetoothDevice) {

      setBluetoothDevice(foundBluetoothDevice)
    }
  }



  return (
    <>
      <Head>
        <title>Waste Scale?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{
        display: 'flex',
        justifyContent: 'center'
      }}>
        <ToggleButtonGroup
          color="primary"
          value={alignment}
          exclusive
          onChange={handleChange}
          aria-label="Platform"
        >
          <ToggleButton value="scale">Scale</ToggleButton>
          <ToggleButton value="data">Data</ToggleButton>
        </ToggleButtonGroup>
      </Box>
      {/* {
        bluetoothDevice !== null
          ? <Scale btDevice={bluetoothDevice} />
          : <Connect onConnectClick={async () => await findDevice()} />
      } */}
      {
        alignment === "scale" ?
          (bluetoothDevice !== null
            ? <Scale btDevice={bluetoothDevice} />
            : <Connect onConnectClick={async () => await findDevice()} />)
          : <Graph></Graph>
      }
      {/*  <Graph /> */}
    </>
  )
}

export default Home
